name: Start Engine
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  start:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install ctype CLI
        run: npm install -g @cloudtype/cli
      - name: Deploy
        run: ctype apply -f trand-doc-engine.yaml
        env:
          CLOUDTYPE_TOKEN: ${{ secrets.CLOUDTYPE_TOKEN }}
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
