name: Stop Engine
on:
  schedule:
    - cron: '0 15 * * *'  # UTC 15:00 = KST 00:00
  workflow_dispatch:
jobs:
  stop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install ctype CLI
        run: npm install -g @cloudtype/cli
      - name: Login
        run: ctype login --token ${{ secrets.CLOUDTYPE_TOKEN }}
      - name: Delete
        run: ctype delete trand-doc-engine
        env:
          CLOUDTYPE_TOKEN: ${{ secrets.CLOUDTYPE_TOKEN }}
